skip bugging executions
qiskit-community/submit-metriq pull request #11
Opened 2023-05-23 20:26 UTC by 1ucian0

With `qiskit-terra==0.23.3`, in the iteration `i==18`, there is a bug in Qiskit that fails like this:
```
qiskit.transpiler.exceptions.TranspilerError: "'swap' would be supported on '(15, 14)' if the direction were swapped, but no rules are known to do that. ['cz', 'rzz', 'swap', 'ryy', 'ecr', 'rzx', 'rxx', 'cx'] can be automatically flipped."
```

This PR skips that case and other `TranspilerError`s.

2023-05-23 21:59 UTC, karlaspuldaro approved these changes
Tested this locally and it solves the issue.

Tracked other iteration skips just to make sure it wasn't skipping too many from the sample size:
```
Qiskit version:  0.23.3
Sample size:  100
Architecture: ibm_rochester
*** Skipping TranspilerError at iteration = 18***
*** Skipping TranspilerError at iteration = 32***
Circuit depth ave: 10.61 | Gate count ave: 16.72

Architecture: rigetti_16q_aspen
*** Skipping TranspilerError at iteration = 55***
*** Skipping TranspilerError at iteration = 74***
Circuit depth ave: 9.12 | Gate count ave: 15.11
```

2023-05-23 22:23 UTC, karlaspuldaro requested changes
While updating the `seed_transpiler` works for version 0.23.3, when not too many iterations encounter an error, this still breaks for previous qiskit-terraversions, see traceback log for 0.22.4:
```
Qiskit version:  0.22.4
Sample size:  100
Architecture: ibm_rochester
*** Skipping TranspilerError at iteration = 1***
*** Skipping TranspilerError at iteration = 3***
*** Skipping TranspilerError at iteration = 4***
*** Skipping TranspilerError at iteration = 12***
*** Skipping TranspilerError at iteration = 13***
*** Skipping TranspilerError at iteration = 26***
*** Skipping TranspilerError at iteration = 29***
*** Skipping TranspilerError at iteration = 34***
*** Skipping TranspilerError at iteration = 37***
*** Skipping TranspilerError at iteration = 41***
*** Skipping TranspilerError at iteration = 42***
*** Skipping TranspilerError at iteration = 47***
*** Skipping TranspilerError at iteration = 49***
*** Skipping TranspilerError at iteration = 57***
*** Skipping TranspilerError at iteration = 60***
*** Skipping TranspilerError at iteration = 63***
*** Skipping TranspilerError at iteration = 69***
*** Skipping TranspilerError at iteration = 74***
Traceback (most recent call last):
(...)
  File "/<python-path>/site-packages/qiskit/transpiler/passes/utils/gate_direction.py", line 136, in _run_coupling_map
    raise TranspilerError(
qiskit.transpiler.exceptions.TranspilerError: "Flipping of gate direction is only supported for ['cx', 'cz', 'ecr'] at this time, not 'swap'."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
(...)
  File "/<python-path>/site-packages/qiskit/transpiler/passes/utils/gate_direction.py", line 136, in _run_coupling_map
    raise TranspilerError(
qiskit.transpiler.exceptions.TranspilerError: "Flipping of gate direction is only supported for ['cx', 'cz', 'ecr'] at this time, not 'swap'."
```
If we skip those fail run results completely, we 'd lose 20% of the samples for both architectures.

2023-05-24 18:54 UTC, 1ucian0 commented
You are very right. It needs to try until success. Fixed in fd7b860010cfab655947733e902294be42233098

2023-05-24 21:02 UTC, karlaspuldaro approved these changes
Thank you! This fix solves transpiler errors in qiskit-terra versions 
0.19.2
0.20.2
0.21.2
0.22.4 
0.23.3

2023-05-25 13:41 UTC, merged